// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/secondary/identity_provider/firebase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Businge931/sba-user-accounts/internal/core/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockFirebaseClient is a mock of FirebaseClient interface.
type MockFirebaseClient struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseClientMockRecorder
}

// MockFirebaseClientMockRecorder is the mock recorder for MockFirebaseClient.
type MockFirebaseClientMockRecorder struct {
	mock *MockFirebaseClient
}

// NewMockFirebaseClient creates a new mock instance.
func NewMockFirebaseClient(ctrl *gomock.Controller) *MockFirebaseClient {
	mock := &MockFirebaseClient{ctrl: ctrl}
	mock.recorder = &MockFirebaseClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseClient) EXPECT() *MockFirebaseClientMockRecorder {
	return m.recorder
}

// CreateCustomToken mocks base method.
func (m *MockFirebaseClient) CreateCustomToken(ctx context.Context, userID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomToken", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomToken indicates an expected call of CreateCustomToken.
func (mr *MockFirebaseClientMockRecorder) CreateCustomToken(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomToken", reflect.TypeOf((*MockFirebaseClient)(nil).CreateCustomToken), ctx, userID)
}

// CreateUser mocks base method.
func (m *MockFirebaseClient) CreateUser(ctx context.Context, email, password, firstName, lastName string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, email, password, firstName, lastName)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockFirebaseClientMockRecorder) CreateUser(ctx, email, password, firstName, lastName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockFirebaseClient)(nil).CreateUser), ctx, email, password, firstName, lastName)
}

// GetUserByEmail mocks base method.
func (m *MockFirebaseClient) GetUserByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockFirebaseClientMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockFirebaseClient)(nil).GetUserByEmail), ctx, email)
}

// SendPasswordResetEmail mocks base method.
func (m *MockFirebaseClient) SendPasswordResetEmail(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendPasswordResetEmail", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendPasswordResetEmail indicates an expected call of SendPasswordResetEmail.
func (mr *MockFirebaseClientMockRecorder) SendPasswordResetEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPasswordResetEmail", reflect.TypeOf((*MockFirebaseClient)(nil).SendPasswordResetEmail), ctx, email)
}

// SendVerificationEmail mocks base method.
func (m *MockFirebaseClient) SendVerificationEmail(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail.
func (mr *MockFirebaseClientMockRecorder) SendVerificationEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockFirebaseClient)(nil).SendVerificationEmail), ctx, email)
}

// UpdatePassword mocks base method.
func (m *MockFirebaseClient) UpdatePassword(ctx context.Context, userID, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, userID, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockFirebaseClientMockRecorder) UpdatePassword(ctx, userID, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockFirebaseClient)(nil).UpdatePassword), ctx, userID, newPassword)
}

// UpdateUser mocks base method.
func (m *MockFirebaseClient) UpdateUser(ctx context.Context, userID string, updates map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, userID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockFirebaseClientMockRecorder) UpdateUser(ctx, userID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockFirebaseClient)(nil).UpdateUser), ctx, userID, updates)
}

// VerifyEmail mocks base method.
func (m *MockFirebaseClient) VerifyEmail(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockFirebaseClientMockRecorder) VerifyEmail(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockFirebaseClient)(nil).VerifyEmail), ctx, token)
}

// VerifyIDToken mocks base method.
func (m *MockFirebaseClient) VerifyIDToken(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockFirebaseClientMockRecorder) VerifyIDToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockFirebaseClient)(nil).VerifyIDToken), ctx, token)
}

// VerifyPassword mocks base method.
func (m *MockFirebaseClient) VerifyPassword(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockFirebaseClientMockRecorder) VerifyPassword(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockFirebaseClient)(nil).VerifyPassword), ctx, email, password)
}

// MockFirebaseAuthProvider is a mock of FirebaseAuthProvider interface.
type MockFirebaseAuthProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseAuthProviderMockRecorder
}

// MockFirebaseAuthProviderMockRecorder is the mock recorder for MockFirebaseAuthProvider.
type MockFirebaseAuthProviderMockRecorder struct {
	mock *MockFirebaseAuthProvider
}

// NewMockFirebaseAuthProvider creates a new mock instance.
func NewMockFirebaseAuthProvider(ctrl *gomock.Controller) *MockFirebaseAuthProvider {
	mock := &MockFirebaseAuthProvider{ctrl: ctrl}
	mock.recorder = &MockFirebaseAuthProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseAuthProvider) EXPECT() *MockFirebaseAuthProviderMockRecorder {
	return m.recorder
}

// ChangePasswordSvc mocks base method.
func (m *MockFirebaseAuthProvider) ChangePasswordSvc(ctx context.Context, userID, oldPassword, newPassword string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePasswordSvc", ctx, userID, oldPassword, newPassword)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePasswordSvc indicates an expected call of ChangePasswordSvc.
func (mr *MockFirebaseAuthProviderMockRecorder) ChangePasswordSvc(ctx, userID, oldPassword, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePasswordSvc", reflect.TypeOf((*MockFirebaseAuthProvider)(nil).ChangePasswordSvc), ctx, userID, oldPassword, newPassword)
}

// LoginSvc mocks base method.
func (m *MockFirebaseAuthProvider) LoginSvc(ctx context.Context, req domain.LoginRequest, user *domain.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginSvc", ctx, req, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginSvc indicates an expected call of LoginSvc.
func (mr *MockFirebaseAuthProviderMockRecorder) LoginSvc(ctx, req, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginSvc", reflect.TypeOf((*MockFirebaseAuthProvider)(nil).LoginSvc), ctx, req, user)
}

// RegisterSvc mocks base method.
func (m *MockFirebaseAuthProvider) RegisterSvc(ctx context.Context, req domain.RegisterRequest) (*domain.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterSvc", ctx, req)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RegisterSvc indicates an expected call of RegisterSvc.
func (mr *MockFirebaseAuthProviderMockRecorder) RegisterSvc(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSvc", reflect.TypeOf((*MockFirebaseAuthProvider)(nil).RegisterSvc), ctx, req)
}

// RequestPasswordResetSvc mocks base method.
func (m *MockFirebaseAuthProvider) RequestPasswordResetSvc(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPasswordResetSvc", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestPasswordResetSvc indicates an expected call of RequestPasswordResetSvc.
func (mr *MockFirebaseAuthProviderMockRecorder) RequestPasswordResetSvc(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPasswordResetSvc", reflect.TypeOf((*MockFirebaseAuthProvider)(nil).RequestPasswordResetSvc), ctx, email)
}

// ResetPasswordSvc mocks base method.
func (m *MockFirebaseAuthProvider) ResetPasswordSvc(ctx context.Context, token, newPassword string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordSvc", ctx, token, newPassword)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ResetPasswordSvc indicates an expected call of ResetPasswordSvc.
func (mr *MockFirebaseAuthProviderMockRecorder) ResetPasswordSvc(ctx, token, newPassword interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordSvc", reflect.TypeOf((*MockFirebaseAuthProvider)(nil).ResetPasswordSvc), ctx, token, newPassword)
}

// VerifyEmailSvc mocks base method.
func (m *MockFirebaseAuthProvider) VerifyEmailSvc(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmailSvc", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmailSvc indicates an expected call of VerifyEmailSvc.
func (mr *MockFirebaseAuthProviderMockRecorder) VerifyEmailSvc(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmailSvc", reflect.TypeOf((*MockFirebaseAuthProvider)(nil).VerifyEmailSvc), ctx, token)
}
