services:
  db:
    image: postgres:16.3
    container_name: sba-users-db
    environment:
      POSTGRES_DB: sba_users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
