// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/secondary/identity_provider/firebase/auth_client_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "firebase.google.com/go/v4/auth"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthClient is a mock of AuthClient interface.
type MockAuthClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthClientMockRecorder
}

// MockAuthClientMockRecorder is the mock recorder for MockAuthClient.
type MockAuthClientMockRecorder struct {
	mock *MockAuthClient
}

// NewMockAuthClient creates a new mock instance.
func NewMockAuthClient(ctrl *gomock.Controller) *MockAuthClient {
	mock := &MockAuthClient{ctrl: ctrl}
	mock.recorder = &MockAuthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthClient) EXPECT() *MockAuthClientMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAuthClient) CreateUser(ctx context.Context, user *auth.UserToCreate) (*auth.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*auth.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthClientMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthClient)(nil).CreateUser), ctx, user)
}

// CustomToken mocks base method.
func (m *MockAuthClient) CustomToken(ctx context.Context, uid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomToken", ctx, uid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomToken indicates an expected call of CustomToken.
func (mr *MockAuthClientMockRecorder) CustomToken(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomToken", reflect.TypeOf((*MockAuthClient)(nil).CustomToken), ctx, uid)
}

// EmailVerificationLink mocks base method.
func (m *MockAuthClient) EmailVerificationLink(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailVerificationLink", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailVerificationLink indicates an expected call of EmailVerificationLink.
func (mr *MockAuthClientMockRecorder) EmailVerificationLink(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailVerificationLink", reflect.TypeOf((*MockAuthClient)(nil).EmailVerificationLink), ctx, email)
}

// GetUserByEmail mocks base method.
func (m *MockAuthClient) GetUserByEmail(ctx context.Context, email string) (*auth.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*auth.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockAuthClientMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockAuthClient)(nil).GetUserByEmail), ctx, email)
}

// PasswordResetLink mocks base method.
func (m *MockAuthClient) PasswordResetLink(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordResetLink", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordResetLink indicates an expected call of PasswordResetLink.
func (mr *MockAuthClientMockRecorder) PasswordResetLink(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordResetLink", reflect.TypeOf((*MockAuthClient)(nil).PasswordResetLink), ctx, email)
}

// UpdateUser mocks base method.
func (m *MockAuthClient) UpdateUser(ctx context.Context, uid string, user *auth.UserToUpdate) (*auth.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, uid, user)
	ret0, _ := ret[0].(*auth.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAuthClientMockRecorder) UpdateUser(ctx, uid, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAuthClient)(nil).UpdateUser), ctx, uid, user)
}

// UpdateUserEmailVerified mocks base method.
func (m *MockAuthClient) UpdateUserEmailVerified(ctx context.Context, uid string, verified bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmailVerified", ctx, uid, verified)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserEmailVerified indicates an expected call of UpdateUserEmailVerified.
func (mr *MockAuthClientMockRecorder) UpdateUserEmailVerified(ctx, uid, verified interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmailVerified", reflect.TypeOf((*MockAuthClient)(nil).UpdateUserEmailVerified), ctx, uid, verified)
}

// VerifyIDToken mocks base method.
func (m *MockAuthClient) VerifyIDToken(ctx context.Context, idToken string) (*auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, idToken)
	ret0, _ := ret[0].(*auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockAuthClientMockRecorder) VerifyIDToken(ctx, idToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockAuthClient)(nil).VerifyIDToken), ctx, idToken)
}

// VerifyPassword mocks base method.
func (m *MockAuthClient) VerifyPassword(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockAuthClientMockRecorder) VerifyPassword(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockAuthClient)(nil).VerifyPassword), ctx, email, password)
}
