// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/secondary/identity_provider/firebase/abstractions.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	auth "firebase.google.com/go/v4/auth"
	firebase "github.com/Businge931/sba-user-accounts/internal/adapters/secondary/identity_provider/firebase"
	gomock "github.com/golang/mock/gomock"
)

// MockFirebaseSDK is a mock of FirebaseSDK interface.
type MockFirebaseSDK struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseSDKMockRecorder
}

// MockFirebaseSDKMockRecorder is the mock recorder for MockFirebaseSDK.
type MockFirebaseSDKMockRecorder struct {
	mock *MockFirebaseSDK
}

// NewMockFirebaseSDK creates a new mock instance.
func NewMockFirebaseSDK(ctrl *gomock.Controller) *MockFirebaseSDK {
	mock := &MockFirebaseSDK{ctrl: ctrl}
	mock.recorder = &MockFirebaseSDKMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseSDK) EXPECT() *MockFirebaseSDKMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockFirebaseSDK) Auth(ctx context.Context) (firebase.FirebaseAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", ctx)
	ret0, _ := ret[0].(firebase.FirebaseAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *MockFirebaseSDKMockRecorder) Auth(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockFirebaseSDK)(nil).Auth), ctx)
}

// MockFirebaseAuth is a mock of FirebaseAuth interface.
type MockFirebaseAuth struct {
	ctrl     *gomock.Controller
	recorder *MockFirebaseAuthMockRecorder
}

// MockFirebaseAuthMockRecorder is the mock recorder for MockFirebaseAuth.
type MockFirebaseAuthMockRecorder struct {
	mock *MockFirebaseAuth
}

// NewMockFirebaseAuth creates a new mock instance.
func NewMockFirebaseAuth(ctrl *gomock.Controller) *MockFirebaseAuth {
	mock := &MockFirebaseAuth{ctrl: ctrl}
	mock.recorder = &MockFirebaseAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFirebaseAuth) EXPECT() *MockFirebaseAuthMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockFirebaseAuth) CreateUser(ctx context.Context, user *auth.UserToCreate) (*auth.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*auth.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockFirebaseAuthMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockFirebaseAuth)(nil).CreateUser), ctx, user)
}

// CustomToken mocks base method.
func (m *MockFirebaseAuth) CustomToken(ctx context.Context, uid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomToken", ctx, uid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomToken indicates an expected call of CustomToken.
func (mr *MockFirebaseAuthMockRecorder) CustomToken(ctx, uid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomToken", reflect.TypeOf((*MockFirebaseAuth)(nil).CustomToken), ctx, uid)
}

// EmailVerificationLink mocks base method.
func (m *MockFirebaseAuth) EmailVerificationLink(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailVerificationLink", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailVerificationLink indicates an expected call of EmailVerificationLink.
func (mr *MockFirebaseAuthMockRecorder) EmailVerificationLink(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailVerificationLink", reflect.TypeOf((*MockFirebaseAuth)(nil).EmailVerificationLink), ctx, email)
}

// GetUserByEmail mocks base method.
func (m *MockFirebaseAuth) GetUserByEmail(ctx context.Context, email string) (*auth.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*auth.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockFirebaseAuthMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockFirebaseAuth)(nil).GetUserByEmail), ctx, email)
}

// PasswordResetLink mocks base method.
func (m *MockFirebaseAuth) PasswordResetLink(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasswordResetLink", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PasswordResetLink indicates an expected call of PasswordResetLink.
func (mr *MockFirebaseAuthMockRecorder) PasswordResetLink(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordResetLink", reflect.TypeOf((*MockFirebaseAuth)(nil).PasswordResetLink), ctx, email)
}

// UpdateUser mocks base method.
func (m *MockFirebaseAuth) UpdateUser(ctx context.Context, uid string, user *auth.UserToUpdate) (*auth.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, uid, user)
	ret0, _ := ret[0].(*auth.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockFirebaseAuthMockRecorder) UpdateUser(ctx, uid, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockFirebaseAuth)(nil).UpdateUser), ctx, uid, user)
}

// VerifyIDToken mocks base method.
func (m *MockFirebaseAuth) VerifyIDToken(ctx context.Context, idToken string) (*auth.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, idToken)
	ret0, _ := ret[0].(*auth.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockFirebaseAuthMockRecorder) VerifyIDToken(ctx, idToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockFirebaseAuth)(nil).VerifyIDToken), ctx, idToken)
}

// MockHTTPClient is a mock of HTTPClient interface.
type MockHTTPClient struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPClientMockRecorder
}

// MockHTTPClientMockRecorder is the mock recorder for MockHTTPClient.
type MockHTTPClientMockRecorder struct {
	mock *MockHTTPClient
}

// NewMockHTTPClient creates a new mock instance.
func NewMockHTTPClient(ctrl *gomock.Controller) *MockHTTPClient {
	mock := &MockHTTPClient{ctrl: ctrl}
	mock.recorder = &MockHTTPClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPClient) EXPECT() *MockHTTPClientMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPClient) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPClientMockRecorder) Do(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPClient)(nil).Do), req)
}

// MockConfigProvider is a mock of ConfigProvider interface.
type MockConfigProvider struct {
	ctrl     *gomock.Controller
	recorder *MockConfigProviderMockRecorder
}

// MockConfigProviderMockRecorder is the mock recorder for MockConfigProvider.
type MockConfigProviderMockRecorder struct {
	mock *MockConfigProvider
}

// NewMockConfigProvider creates a new mock instance.
func NewMockConfigProvider(ctrl *gomock.Controller) *MockConfigProvider {
	mock := &MockConfigProvider{ctrl: ctrl}
	mock.recorder = &MockConfigProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigProvider) EXPECT() *MockConfigProviderMockRecorder {
	return m.recorder
}

// GetAPIKey mocks base method.
func (m *MockConfigProvider) GetAPIKey() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIKey")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockConfigProviderMockRecorder) GetAPIKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockConfigProvider)(nil).GetAPIKey))
}

// GetHTTPTimeout mocks base method.
func (m *MockConfigProvider) GetHTTPTimeout() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHTTPTimeout")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetHTTPTimeout indicates an expected call of GetHTTPTimeout.
func (mr *MockConfigProviderMockRecorder) GetHTTPTimeout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHTTPTimeout", reflect.TypeOf((*MockConfigProvider)(nil).GetHTTPTimeout))
}

// GetProjectID mocks base method.
func (m *MockConfigProvider) GetProjectID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProjectID indicates an expected call of GetProjectID.
func (mr *MockConfigProviderMockRecorder) GetProjectID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectID", reflect.TypeOf((*MockConfigProvider)(nil).GetProjectID))
}

// GetServiceAccountKeyPath mocks base method.
func (m *MockConfigProvider) GetServiceAccountKeyPath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceAccountKeyPath")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetServiceAccountKeyPath indicates an expected call of GetServiceAccountKeyPath.
func (mr *MockConfigProviderMockRecorder) GetServiceAccountKeyPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceAccountKeyPath", reflect.TypeOf((*MockConfigProvider)(nil).GetServiceAccountKeyPath))
}

// GetStorageBucket mocks base method.
func (m *MockConfigProvider) GetStorageBucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageBucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStorageBucket indicates an expected call of GetStorageBucket.
func (mr *MockConfigProviderMockRecorder) GetStorageBucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageBucket", reflect.TypeOf((*MockConfigProvider)(nil).GetStorageBucket))
}
